service/models/order.py, service/routes.py, tests/factories.py, tests/test_models.py, tests/test_routes.py
[General Setup](https://app.zenhub.com/workspaces/orders-fa24-001-66e8cb3a2927b200175203c9/issues/gh/csci-ga-2820-fa24-001/orders/27) for Test Driven Development.
=> Updated factories.py for tetsing set up and did some general clean up

service/routes.py, tests/test_routes.py
This PR addresses the two issues "Create Order" and "Read Order (by order id)".
1. Added **create_order()** in routes.py.
2. Added **test_create_order()** in test_routes.py
3. Added **read_order()** in routes.py which is responsible for fetching an order by its unique ID
4. Added **test_read_order()** in test_routes.py
resolve #4 
resolve #23
=> Create Order and Read Order

service/routes.py, tests/test_models.py, tests/test_routes.py
Made the following changes:
-Added create item endpoint in routes.py
-Added test create item endpoint in test_routes.py
=> added create item endpoint

service/routes.py, tests/test_routes.py
Made the following changes:
-Added get item endpoint in routes.py
-Added test get item endpoint in test_routes.py
=> Add get item

service/models/item.py, service/models/order.py, tests/test_item.py, tests/test_order.py
Changes:
1. Added test_item.py
2. deleted test_models.py
3. added a few lines in deserialize block for item.py
=> created test_item.py and modified files accordingly

service/models/item.py
=> fixing item deserialization

service/routes.py, tests/test_routes.py
Changes:
1. Route for List all orders added
2. Test for List all orders added
=> added route for list all orders

service/routes.py, tests/test_routes.py
Changes:
1. Added method to list all items in order with ordre_id
2. Added tests for it
=> added method to list all items in the order with order_id

tests/test_item.py
Removed assert statement for test_item.py whihc was missed in one of the previous PRs: https://github.com/CSCI-GA-2820-FA24-001/orders/pull/41
=> bug fix: test_item.py fixed

service/routes.py, tests/test_routes.py
Updating item in an order
- route 
- test
=> Update item route and test

service/models/item.py, service/models/order.py, service/models/persistent_base.py, service/routes.py, tests/test_order.py, tests/test_persistent_base.py, tests/test_routes.py
changes:
fixing linting issues and general cleanup
=> fixing linting issues and general cleanup

service/__init__.py, service/models/__init__.py, service/models/order.py, tests/factories.py, tests/test_order.py, tests/test_routes.py
Added enum for order_status and their respective test_cases
=> added enum for order status and the test cases

service/models/order.py, service/routes.py, tests/test_order.py, tests/test_routes.py
I realize that there is an update status method as well added by @Kirei-Nan but was hoping that we could keep this one separate as it is an ACTION and using a PUT verb and not an update primarily. Let me know what you guys think!
=> added action to cancel order using PUT method

service/models/order.py, service/routes.py, tests/test_order.py, tests/test_routes.py
resolve #9 
Replaced the find_by_name() and find_by_status() method in the Order model with find_by_filters(). 
The new method supports passing customer_name, status and product_name as parameters. 
If a parameter is not None, it will be used as a filter condition. 
This implementation supports multi-criteria query.
=> Read Order (By Product) 

service/models/order.py, service/routes.py, tests/test_order.py, tests/test_routes.py
Fixed lint errors and tested using 'make lint'
=> Fixing linting errors

service/models/order.py, service/routes.py, tests/test_order.py, tests/test_routes.py
Reverts CSCI-GA-2820-FA24-001/orders#72
=> Revert "Fixing linting errors"

service/models/order.py, service/routes.py, tests/test_order.py, tests/test_routes.py
Fixed linting errors and tested using make lint
=> Fixed linting errors

Dockerfile, k8s/deployment.yaml, k8s/ingress.yaml, k8s/postgres.yaml, k8s/pv.yaml, k8s/secret.yaml, k8s/service.yaml, requirements.txt, service/routes.py, tests/test_routes.py
This branch implements a fully functional microservice deployed in Kubernetes. The following features have been completed:
1. Configured PostgreSQL as the database for the microservice using a StatefulSet.
2. Organized Kubernetes manifests under the k8s/ directory:
- deployment.yaml: Defines the application's deployment.
- ingress.yaml: Configures external access to the application.
- postgres.yaml: Manages the PostgreSQL StatefulSet and related resources.
- pv.yaml: Configures PersistentVolumes for PostgreSQL.
- secret.yaml: Stores sensitive configuration like database credentials.
- service.yaml: Exposes the application and database within the cluster.
3. Added a /health endpoint for readiness and liveness probes.
4. Verified that the application runs successfully in the local …
=> 78 deploy to kubernetes

features/orders.feature
Added BDD test for delete feature and tested using behave
=> Added delete scenario

features/orders.feature
Added test for List orders feature and tested using behave
=> Added test for list all orders

features/orders.feature
Added test for update_order and tested with behave
=> BDD test for update order

features/environment.py, features/orders.feature
Add Cancel Order test and fix Chrome stability
=> Add Cancel Order test and fix Chrome stability

features/orders.feature, features/steps/web_steps.py
Added changes needed for Item based BDD tests 
Added test for Read Item
=> Changes for Item BDD tests and Read Item test

features/orders.feature, features/steps/web_steps.py, service/static/js/rest_api.js
UI was done, just needed to add bdd testing for deleting an item
=> added bdd tetsing for deleting item

service/routes.py, tests/test_query_actions.py
modified tests to improve coverage
=> tests modified

Makefile, features/orders.feature, features/steps/web_steps.py, service/static/css/styles.css, service/static/index.html, service/static/js/rest_api.js
=> frontend refactoring

service/static/index.html
make the button name "update" instead of "save"
Solve #127
=> modify button name
